### ISSUE TITLE
How would you add a client side?

### ISSUE THREAD

**Issue by safarista** [ianmurrays/active_invoices#1]
I know this is going to be a huge question but I'll ask anyway.

Say I want my clients to login and pay for their invoices. How would I go about using the same AA interface or other namespace to create a client end?

**Comment by ianmurrays** [comment]
Sounds kinda complicated to do with active admin directly. You could create an interface and use CanCan (an authorization gem), but I'm not sure of the progress on that, since someone was trying to add integration of this gem to Active Admin.

## 

Ian Murray S.
Twitter: @Synt4x
GitHub: ianmurrays
Skype: ianmurrays

**Comment by ianmurrays** [comment]
Did you come up with a solution for this? Would be great to include this in the repo.

**Comment by demogar** [comment]
I believe this is pretty doable (as today).

As @ianmurrays says, you need CanCan and a role for Clients (with CanCan you'll control what the user can do/manage based on the role). As today, AA works great along with CanCan, so this is a plus.

You then will need a custom action for "pay" the Invoice, this invoice will be enabled for Users where role => "client" and that's all.

I could provide this, if interested. Just need some spare time, hehe.

**Comment by ianmurrays** [comment]
@demogar If you ever find time to add this, that'd be great. For now, I'm closing this issue. Feel free to reopen!
